### ISSUE TITLE
Preview for individual clips

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/komposition#23]
Right now you can only preview sequences and parallels, not individual clips. It would be very useful to preview individual clips, preferably implemented using the same machinery as the current preview.

Related to #11.

**Comment by Cmdv** [comment]
I took a look at this but couldn't quite work out some parts.

can see I need to add something like `SomeVideoPart v -> ??` here:
https://github.com/owickstrom/komposition/blob/f4db3f0547127f3f2cdfd7de0f4be22847ddd70d/src/Komposition/Application/TimelineMode.hs#L335-L341

I need `Maybe Render.Composition` but I have `VideoPart ()` so not too sure how to get to that.

Feel like something in this function should help [here](https://github.com/owickstrom/komposition/blob/master/src/Komposition/Render/Composition.hs#L89)?
