### ISSUE TITLE
Make it build in pure Nix sandbox

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/komposition#29]
I have messed around with Nix, and gotten some stuff to work, but I think that was because I had dependencies installed globally as APT packages. Would be nice if someone wanted to help out and make the Nix setup work on its own, with required dependencies like `ffmpeg`, `sox`, `libgtk`, etc. Those should be defined in the CI build very soon.

**Comment by tazjin** [comment]
There are multiple ways to deal with the combination of Haskell & Nix.

For one, there are tools like [stack2nix](https://github.com/input-output-hk/stack2nix) which take entire Stack configurations (including pinned commits, which Komposition seems to have for some deps) and generate pretty large Nix expressions (for every dependency) from it. I've never used this approach myself, but it has the advantage that it doesn't lock dependency version management in to Nix.

Another way is to use, for example, [cabal2nix](https://github.com/NixOS/cabal2nix) instead to generate Nix expressions that use the dependencies packaged in `nixpkgs`' own Haskell package set. Custom dependencies that are not on Hackage would need to be added. This results in smaller Nix expressions, nice dependency caching behaviour (everything that's on Hackage is pre-built and available), automatic resolution of native libraries for everything that's in Hackage but comes at the cost that dependency versions are now more dependent on Nix.

You can also package Haskell things [manually](https://github.com/Gabriel439/haskell-nix), but this approach (while "clean") seems a bit difficult for a package with many dependencies and foreign links.

I guess what I'm asking is, what are your goals:

1. Use Nix for CI runs
2. Package Komposition in `nixpkgs`
3. Use Nix as the primary development flow tool
4. Use Nix and something else (Stack?) as *equivalent options* for the developer workflow

... anything else?

**Comment by owickstrom** [comment]
Yes, `cabal2nix` is the approach I've been using (see https://github.com/owickstrom/komposition/blob/master/default.nix). What's currently missing in that setup is the non-Haskell dependencies, both libraries and command-line tools that needs to be on the PATH.

I'd say the goals would be, in decreasing order of importance:

1. Allow developers to run `nix-shell` and have a fully setup development environment
2. Be install a package with Nix, like with `cachix`: https://github.com/cachix/cachix#installation
3. Get it into `nixpkgs`

I'm not using Nix and Stack together, so I have no interest in that, really. Maybe others do?

**Comment by tazjin** [comment]
> I'm not using Nix and Stack together, so I have no interest in that, really. Maybe others do?

NixOS users generally will (if they're using Stack) because most of us have `nix.enable: true` set globally as we run into a bunch of issues with how Stack fetches GHC otherwise.

A `cabal2nix`-generated expression is usually good enough for invoking `nix-shell` and having a compiler with all dependencies installed, but if you also want to build local Hoogle etc. I think the generated expression has to be modified.

Do you use Stack when developing?

**Comment by owickstrom** [comment]
> NixOS users generally will (if they're using Stack) because most of us have nix.enable: true set globally as we run into a bunch of issues with how Stack fetches GHC otherwise.

OK. If we can add the relevant packages to the `stack.yaml` so that it also works for them, that would be nice.

> A cabal2nix-generated expression is usually good enough for invoking nix-shell and having a compiler with all dependencies installed, but if you also want to build local Hoogle etc. I think the generated expression has to be modified.

That's already done here:

https://github.com/owickstrom/komposition/blob/7d3770639b74ff173be8b62f796125d4e3c89ad8/default.nix#L37-L42

> Do you use Stack when developing?

I have been using it for Komposition when developing on Windows. On Ubuntu I use Nix, and sometimes Stack for other small projects.

**Comment by owickstrom** [comment]
Closed by #37. Stack+Nix support can be handled as a separate issue, IMO.
