### ISSUE TITLE
Change import checkbox label

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/komposition#3]
Currently it's called "Split video" or something like that. Should be "Automatically classify parts", and the code identifiers should reflect that.

**Comment by JasonMFry** [comment]
Recommend closing, looks like it was done in [this commit](https://github.com/owickstrom/komposition/commit/9ebaf93727c3695c325d86a6f0b1c9745e67406d), https://github.com/owickstrom/komposition/blob/234584948ccaf1d1750f2503f9d463e58929bb43/src/Komposition/UserInterface/GtkInterface/ImportView.hs#L43

**Comment by owickstrom** [comment]
Yes, you're absolutely right. The identifiers in the code should be fixed as well. I did this in a hurry before recording the tutorial screencast. 😊
