### ISSUE TITLE
Clicking 'Project > Import Assets' crashes app (without GNOME installed prior)

### ISSUE THREAD

**Issue by andrewmcveigh** [owickstrom/komposition#35]
**Describe the bug**
Clicking 'Project > Import Assets' crashes app (without GNOME installed prior)

**To Reproduce**
1. Have NixOS installed, XMonad, no desktop manager, GTK, GNOME, etc.
2. Install komposition as per https://twitter.com/owickstrom/status/1047579032148213761
3. `$ komposition`
4. Click 'Project > Import Assets'
5. crash, error reported in terminal (paste below)

**Expected behavior**
Open file manager maybe? - I guess I don't have a default desktop one.

```
(komposition:22895): Gtk-WARNING **: 22:01:28.288: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(komposition:22895): GLib-GIO-ERROR **: 22:01:29.837: No GSettings schemas are installed on the system
[1]    22895 trace trap  komposition
```

**Desktop (please complete the following information):**
 - OS: NixOS 18.09
 - Komposition version or commit: 5536628a682026487ecd7b3a54e0cfec1e151386
 - See https://twitter.com/owickstrom/status/1047579032148213761

**Comment by owickstrom** [comment]
Thank you so much for the report!

I think I managed to reproduce this using a pure Nix shell:

```sh
# in the repository:
$ nix-shell --pure -p '(import ./. {}).komposition'
[nix-shell]$ komposition
```

And by following your steps, when clicking the file selection button, I also got:

```
(komposition:12373): GLib-GIO-ERROR **: 08:06:31.684: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```

I think it's caused by the Nix derivation missing some dependencies, but I'm not sure. I could also be that Komposition is using [`FileChooserNative`](https://hackage.haskell.org/package/gi-gtk-3.0.17/docs/GI-Gtk-Objects-FileChooserNative.html), and that it requires something special to work.

**Comment by owickstrom** [comment]
Got further on this one, probably have a PR ready soon.

**Comment by owickstrom** [comment]
@andrewmcveigh mind trying https://github.com/owickstrom/komposition/pull/37? Instructions available in description.

**Comment by andrewmcveigh** [comment]
Yes, #37 fixes the crash. The open file dialog comes up and allows me to import a clip. :+1:

**Comment by owickstrom** [comment]
@andrewmcveigh Lovely. I think it should now support preview and rendering, as well. :+1:
