### ISSUE TITLE
user error (Couldn't create GStreamer GTK sink.)

### ISSUE THREAD

**Issue by danbroooks** [owickstrom/komposition#45]
On attempting to preview a parallel in Komposition, the application crashes, and in the terminal it says:

```
komposition: user error (Couldn't create GStreamer GTK sink.)
```

Is this due to a missing library on my system possibly? Anything gstreamer related from the install appears to be fine:

```
sudo apt-get install gstreamer1.0-libav  gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gstreamer1.0-plugins-base is already the newest version (1.14.1-1ubuntu1~ubuntu18.04.1).
gstreamer1.0-plugins-good is already the newest version (1.14.1-1ubuntu1~ubuntu18.04.1).
gstreamer1.0-libav is already the newest version (1.14.1-1~ubuntu18.04.1).
gstreamer1.0-plugins-bad is already the newest version (1.14.1-1ubuntu1~ubuntu18.04.1).
0 to upgrade, 0 to newly install, 0 to remove and 128 not to upgrade.
```

Not too sure how to debug this beyond that.

**Comment by owickstrom** [comment]
It does look you have everything, but try running the following command:

```sh
gst-inspect-1.0 gtksink
```

You should see a large listing of information and properties if it's installed.

The `gtksink` is the GStreamer plugin used when displaying the preview. I would expect it to be in the `good` or `bad` plugins. I've had similiar problems on various operating systems and I'm quite confused by the gst-plugins distribution.

**Comment by danbroooks** [comment]
Yeah that gives me:

```
λ ~ gst-inspect-1.0 gtksink
No such element or plugin 'gtksink'
```

**Comment by danbroooks** [comment]
[This page](https://thiblahute.github.io/GStreamer-doc/frequently-asked-questions/using.html?gi-language=c#chapter-getting) says 'If this tells you that there is "no such element or plugin", you haven't installed GStreamer correctly. Please check how to get GStreamer'.

I'll investigate further on the GStreamer side of things, if there is anything I find relevant to this project I will submit a PR :+1:

**Comment by owickstrom** [comment]
Perfect, might need some changes to the install instructions. Thanks @danbroooks :+1:

**Comment by danbroooks** [comment]
I think this is due to a missing gstreamer dep, however I still can't get the preview functionality to work. The preview box will open, however the video doesn't play, and I get this output in the terminal:

```
ffmpeg -v quiet -stats -nostdin -i /tmp/project.komposition-8cb1ece599fdf306/HKT Video.flv -f lavfi -i aevalsrc=0:duration=238.733 -filter_complex [0:v:0]trim=start=0.0:duration=238.733,scale=width=960:height=540:force_original_aspect_ratio=disable,setpts=PTS-STARTPTS[v0];[1:a:0]asetpts=PTS-STARTPTS[a1];[v0]concat=n=1:v=1:a=0,setpts=PTS-STARTPTS[video];[a1]concat=n=1:v=0:a=1,asetpts=PTS-STARTPTS[audio] -map [video] -map [audio] -f matroska -framerate 25 -vcodec h264 -acodec aac -listen 1 http://localhost:12345
Could not establish connection to server. (5): Could not establish connection to server.
Internal data stream error. (1): Internal data stream error.
Stream doesn't contain enough data. (4): Stream doesn't contain enough data.
```

Then when I close the preview window and attempt to play again, I get this output, followed by the application crashing:

```
ffmpeg -v quiet -stats -nostdin -i /tmp/project.komposition-8cb1ece599fdf306/HKT Video.flv -f lavfi -i aevalsrc=0:duration=238.733 -filter_complex [0:v:0]trim=start=0.0:duration=238.733,scale=width=960:height=540:force_original_aspect_ratio=disable,setpts=PTS-STARTPTS[v0];[1:a:0]asetpts=PTS-STARTPTS[a1];[v0]concat=n=1:v=1:a=0,setpts=PTS-STARTPTS[video];[a1]concat=n=1:v=0:a=1,asetpts=PTS-STARTPTS[audio] -map [video] -map [audio] -f matroska -framerate 25 -vcodec h264 -acodec aac -listen 1 http://localhost:12345

ERROR: Caught a segmentation fault while loading plugin file:
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```

Any clues?

The missing dep was `gstreamer1.0-gtk3`, and I have added this to `docs/src/installation.md`, however I'd like to get this working and submit a single PR (I'm thinking it's likely perhaps another missing lib or install step, I'm just not sure what, and googling has failed me :disappointed:)

**Comment by owickstrom** [comment]
The first thing I think I saw before, which seems like a timing issue. That should probably be its own reported issue.

The second thing I haven't seen before in this way, but I had segfaults in gstreamer plugins when I had a bad setup, where mixed Nix and Ubuntu dependencies were being linked. I guess you're not experiencing that exact problem, but might be a hint. I've also found these things very hard to debug. :disappointed:

**Comment by danbroooks** [comment]
Yeah I think this is to do with `ffmpeg` and the way the arguments to the command are being passed in. I feel like the second error might be due to the fact that ffmpeg is failing first time round.

I'll open a PR for the missing dep thing, and an issue for this `ffmpeg` problem :+1:
