### ISSUE TITLE
Unable to Install on OSX 10.14.3 (Mojave)

### ISSUE THREAD

**Issue by Cmdv** [owickstrom/komposition#70]
**Describe the bug**
Unsure if related to #38 but when building using Stack to install on OSX 10.14.3, running `stack install`

**To Reproduce**

1. `Brew install ....`
2. `stack build happy`
3. `stack install`
4. See error messages

**Expected behavior**
Should build :)

**Error Messages**

```
Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'gobject-introspection-1.0', not found
```

So I tried to install manually with `stack build libffi` and was received following error:
```
Configuring libffi-0.1...
    clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
    Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3: The pkg-config package 'libffi' is
    required but it could not be found.
```
so thought I'll try `stack build` on it's own and the following error is shown:
```
Configuring haskell-gi-0.21.3...
    clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
    Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3: '/usr/local/bin/pkg-config' exited
    with an error:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'gobject-introspection-1.0', not found
```
 
**Desktop (please complete the following information):**
 - OS: OSX 10.14.3
 - Komposition v ?? (latest as of 7 jan 2018)
 - Build environment Stack

**Comment by owickstrom** [comment]
Hi! This looks like you're missing some system dependencies. I see you have run `brew install`, but it might be that the list of dependencies at https://owickstrom.github.io/komposition/user-guide/installation/#macos is incomplete. Can you try installing `libffi` with Homebrew?

**Comment by Cmdv** [comment]
🎉 that worked, wasn't sure where the library came from so assumed it was a Haskell one!
I then noticed that `libffi` was missing from the install script in the docs and probably why it didn't install in the first place.
