### ISSUE TITLE
Add ability to edit audio durations

### ISSUE THREAD

**Issue by Cmdv** [owickstrom/komposition#80]
When Audio clip is selected add a `Start/End` to the sidebar menu to be able to edit the start and end of an audio clip much like you currently can with video.

<img width="401" alt="screenshot 2019-01-19 at 14 26 57" src="https://user-images.githubusercontent.com/3036557/51428031-b723eb00-1bf6-11e9-90bf-34cd1c455b7c.png">

**Comment by owickstrom** [comment]
This one is tricky. Current classification uses SOX, which doesn't give the classified timestamps of each "sentence", but merely outputs a lot of audio files for each of them. I've been contemplating writing a custom classifier for audio but I've not had the time.

**Comment by owickstrom** [comment]
Indeed. :( Could possibly use Sox as a library and retrieve the timestamps
somehow, but haven't looked into that.

Den ons 23 jan. 2019 14:28 skrev Vincent Orr <notifications@github.com>:

**Comment by owickstrom** [comment]
Closing this for now. Thanks!

**Comment by Cmdv** [comment]
no worries need to revisit this project, it was fun to work on last time 😃

**Comment by owickstrom** [comment]
Me, too. I've been quite inactive the past 6 months.
