### ISSUE TITLE
Can't install on MacOS

### ISSUE THREAD

**Issue by ad-si** [owickstrom/komposition#89]
**Describe the bug**
I ran the installation instruction from the website, but I get following errror after running `stack install`:

```
--  While building package gi-gio-2.0.18 using:
      /private/var/folders/fm/dv6_x7h166n8694zz_yn0mmc0000gn/T/stack-5e089fb0874aa3fe/gi-gio-2.0.18/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-2.2.0.1 configure --with-ghc=/Users/adrian/dotfiles/home/stack/programs/x86_64-osx/ghc-8.4.3/bin/ghc --with-ghc-pkg=/Users/adrian/dotfiles/home/stack/programs/x86_64-osx/ghc-8.4.3/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/adrian/dotfiles/home/stack/snapshots/x86_64-osx/lts-12.4/8.4.3/pkgdb --package-db=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/pkgdb --libdir=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/lib --bindir=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/bin --datadir=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/share --libexecdir=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/libexec --sysconfdir=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/etc --docdir=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/doc/gi-gio-2.0.18 --htmldir=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/doc/gi-gio-2.0.18 --haddockdir=/Users/adrian/Tests/komposition/.stack-work/install/x86_64-osx/lts-12.4/8.4.3/doc/gi-gio-2.0.18 --dependency=Cabal=Cabal-2.2.0.1-3NZenIS6TKq4wbIU8rPEqU --dependency=base=base-4.11.1.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.5.11.0 --dependency=gi-glib=gi-glib-2.0.17-BGKu2O63boo3ER0DgAu7qb --dependency=gi-gobject=gi-gobject-2.0.16-9VEhCTt2AXXENAxwhR0DZC --dependency=haskell-gi=haskell-gi-0.21.3-5BHk574AXr0DJeWLooizaZ --dependency=haskell-gi-base=haskell-gi-base-0.21.1-8hOUmSO3PcDBK7C9kaBigg --dependency=haskell-gi-overloading=haskell-gi-overloading-1.0-6w3IXGDooXgu3RA2LfTuf --dependency=text=text-1.2.3.0 --dependency=transformers=transformers-0.5.5.0
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/adrian/Tests/komposition/.stack-work/logs/gi-gio-2.0.18.log

    [1 of 2] Compiling Main             ( /private/var/folders/fm/dv6_x7h166n8694zz_yn0mmc0000gn/T/stack-5e089fb0874aa3fe/gi-gio-2.0.18/Setup.hs, /private/var/folders/fm/dv6_x7h166n8694zz_yn0mmc0000gn/T/stack-5e089fb0874aa3fe/gi-gio-2.0.18/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /Users/adrian/dotfiles/home/stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/fm/dv6_x7h166n8694zz_yn0mmc0000gn/T/stack-5e089fb0874aa3fe/gi-gio-2.0.18/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup/StackSetupShim.o )
    Linking /private/var/folders/fm/dv6_x7h166n8694zz_yn0mmc0000gn/T/stack-5e089fb0874aa3fe/gi-gio-2.0.18/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup/setup ...
    clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
    clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
    Could not resolve symbol "g_desktop_app_info_lookup_get_type" in namespace "Gio"
    CallStack (from HasCallStack):
      error, called at lib/Data/GI/CodeGen/LibGIRepository.hs:167:8 in haskell-gi-0.21.3-5BHk574AXr0DJeWLooizaZ:Data.GI.CodeGen.LibGIRepository
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Komposition commit: 66d6d611289a944a67625c2f36ca8d66768007f9

**Comment by pranaysashank** [comment]
+1
Were you able to resolve this? I ran into the same issue trying to build gi-gtk on macOS 10.14.3.

**Comment by owickstrom** [comment]
Sorry I don't have a Mac available to test on. This does look very much like https://github.com/owickstrom/komposition/issues/85, where `gobject-introspection` had not been installed. Can you verify if you have the same problem?

**Comment by pranaysashank** [comment]
The problem is with the upstream glib library. Here's a workaround https://github.com/haskell-gi/haskell-gi/issues/218

**Comment by owickstrom** [comment]
Did anyone get this to work?

**Comment by ad-si** [comment]
Nope, not yet. The workaround seemed to fix the first error, but I got another one…

**Comment by vilinski** [comment]
Hi, I'm also struggling to install on MacOS Catalina.

one command mentioned in the installation instruction is failed on my mac:

`brew install gst-plugins-good --with-gtk+3`

>Error: invalid option: --with-gtk+3

Tried to install it without this options

`brew install gst-plugins-good`

but finally `stack install` didn't worked for me also. Don't know whether the error is related to the previous. Are there any hints what to look at?

<details>
  <summary>stack install output.</summary>
  <pre>
$ stack install
gi-pango          > configure
gi-pango          > [1 of 2] Compiling Main             ( /private/var/folders/89/kmz0d66952vf0kl_f95zcc2m0000gn/T/stack12175/gi-pango-1.0.19/Setup.hs, /private/var/folders/89/kmz0d66952vf0kl_f95zcc2m0000gn/T/stack12175/gi-pango-1.0.19/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/Main.o )
gi-pango          > [2 of 2] Compiling StackSetupShim   ( /Users/avilinski/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/89/kmz0d66952vf0kl_f95zcc2m0000gn/T/stack12175/gi-pango-1.0.19/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/StackSetupShim.o )
gi-pango          > Linking /private/var/folders/89/kmz0d66952vf0kl_f95zcc2m0000gn/T/stack12175/gi-pango-1.0.19/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/setup ...
gi-pango          > Configuring gi-pango-1.0.19...
gi-pango          > setup: An 'autogen-module' is neither on 'exposed-modules' or 'other-modules'.
gi-pango          >

--  While building package gi-pango-1.0.19 using:
      /private/var/folders/89/kmz0d66952vf0kl_f95zcc2m0000gn/T/stack12175/gi-pango-1.0.19/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/pkgdb --libdir=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/lib --bindir=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/bin --datadir=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/share --libexecdir=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/libexec --sysconfdir=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/etc --docdir=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/doc/gi-pango-1.0.19 --htmldir=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/doc/gi-pango-1.0.19 --haddockdir=/Users/avilinski/.stack/snapshots/x86_64-osx/362b730d790cab2c4ae90f4e46ab1c67cf6896e43dafabe25ac40f00f0a5c97b/8.6.5/doc/gi-pango-1.0.19 --dependency=Cabal=Cabal-2.4.1.0-IBbax5zHztPeovxF8fJKx --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 --dependency=gi-glib=gi-glib-2.0.17-He3SeHEEYb1DWiT4TpX9ev --dependency=gi-gobject=gi-gobject-2.0.19-HLSOgyjJxUE2zYdtgISec5 --dependency=haskell-gi=haskell-gi-0.21.5-B7oEYie8Wik99xbtCPMhIP --dependency=haskell-gi-base=haskell-gi-base-0.21.5-B7L3HQFSPkOFeLcsLCK63O --dependency=haskell-gi-overloading=haskell-gi-overloading-1.0-6w3IXGDooXgu3RA2LfTuf --dependency=text=text-1.2.3.1 --dependency=transformers=transformers-0.5.6.2 --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1
  </pre>
</details>

**Comment by athas** [comment]
Works for me with `cabal install` now.  Maybe bumping to a newer `stack` snapshot will work?

**Comment by owickstrom** [comment]
Anyone else that can confirm it works on macOS now?

**Comment by athas** [comment]
It will fail with the current stack.yaml, but should work with the following (which uses GHC 8.8.1):

```
resolver: nightly-2019-12-29

packages:
- .

extra-deps:
- ffmpeg-light-0.12.2.2
- fused-effects-0.1.2.1
- gi-atk-2.0.21
- gi-cairo-1.0.23
- gi-gdk-3.0.22
- gi-gdkpixbuf-2.0.23
- gi-gio-2.0.25
- gi-glib-2.0.23
- gi-gobject-2.0.22
- gi-graphene-1.0.1
- gi-gsk-4.0.1
- gi-gst-1.0.22
- gi-gtk-3.0.32
- gi-gtk-declarative-0.6.2
- gi-pango-1.0.22
- indexed-extras-0.2
- massiv-0.2.5.0
- massiv-io-0.1.9.0
- motor-0.4.0
- row-types-0.3.0.0

allow-newer: true
```

**Comment by athas** [comment]
If you just want to get a working Komposition on macOS, then try `brew install komposition`.

**Comment by ad-si** [comment]
Nice, `brew install komposition` works for me. This fixes the issue for me. Feel free to close it 🙃
