### ISSUE TITLE
Fails to build with GHC 8.8.1

### ISSUE THREAD

**Issue by athas** [owickstrom/komposition#95]
**Describe the bug**
`komposition` cannot build with GHC 8.8.1.  The problem is primarily a dependency on an old version of `fused-effects` that has a restrictive upper bound on `base`.  I tried fixing it myself, but `fused-effects` changes enormously between API versions, so I cannot figure out how.  Hopefully 1.0 will be more stable.

**To Reproduce**
`cabal build` with GHC 8.8.1.

**Expected behavior**
A successful build.

**Desktop (please complete the following information):**
 - OS: macOS whatever the newest is.
 - Komposition HEAD
 - `cabal` 3.

**Comment by athas** [comment]
(My context is that I'm trying to get `komposition` to build on macOS and added to Homebrew, but that will require building with Cabal using the newest version of GHC.)

**Comment by athas** [comment]
The fused-effects maintainers [issued a revision that makes version 0.1.2.1 work with GHC 8.8.1](https://github.com/fused-effects/fused-effects/issues/336), so once #96 is merged, `komposition` should build with GHC 8.8.1.

**Comment by owickstrom** [comment]
@athas Thanks for your research into this. I've not had time to upgrade Komposition to the new version of fused-effects. Hopefully I can find some time and work through it soon.

**Comment by owickstrom** [comment]
Also, a Homebrew build would be very cool!

**Comment by athas** [comment]
I have verified that komposition now builds with GHC 8.8.1.
